---
title: "Causal forest model for isolation"
author: "Ryunosuke Goto"
date: "10/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(ggplot2)
library(arsenal)
library(gridExtra)
library(ggpubr)
library(cowplot)
library(grid)
library(MASS)
library(knitr)
library(igraph)
library(data.table)
library(Rtsne)
library(caret)
library(pdp)
library(dtwclust)
library(randomForest)

rootdir <- system("git rev-parse --show-toplevel", intern=TRUE)[1]

source(paste(rootdir,"R/degree.R",sep="/"))
sampleList <- degree(redo=TRUE) #set redo=TRUE to update

sample.reg = sampleList[[4]]

#define isolation
sample.reg$isolated = ifelse(sample.reg$degree.1<=1 | sample.reg$degree.2<=1 | sample.reg$degree.3<=1 | sample.reg$degree.4<=1 | sample.reg$degree.5<=1| sample.reg$degree.6<=1 | sample.reg$degree.7<=1 | sample.reg$degree.8<=1 | sample.reg$degree.9<=1 | sample.reg$degree.10<=1, 1, 0)
```

#GRF model
```{r grf}
library(grf)
num.rankings <- 5
num.folds <- 5


set.seed(1111)


sample.cf = sample.reg[sample.reg$inequality=="low" | sample.reg$inequality=="high",]
sample.cf = sample.cf[,c(
  "ID","isolated","behavior.1","degree.0","coefLocal.0","coefGlobal.0","alterPrevDegree.1","visibleWealth","wealth","inequality"
)]
sample.cf = sample.cf[complete.cases(sample.cf),]
sample.cf$isolated = as.numeric(sample.cf$isolated)
sample.cf$behavior.1 = ifelse(sample.cf$behavior.1=="D",1,0)
sample.cf$wealth = ifelse(sample.cf$wealth=="rich",1,0)
sample.cf$inequality = ifelse(sample.cf$inequality=="high",1,0)

n<-nrow(sample.cf)
folds <- sample(c(1:num.folds), replace=TRUE, size=n)

Y.isolated <-  sample.cf$isolated
X.isolated <-  sample.cf[,c(
  "degree.0","coefLocal.0","coefGlobal.0","alterPrevDegree.1","visibleWealth","wealth","inequality"
)]
W.isolated <-  sample.cf$behavior.1


#causal forest with folds
cf.isolated <- causal_forest(X.isolated, Y.isolated, W.isolated, 
                            honesty = TRUE, 
                            clusters=folds,
                            seed=1)

test_calibration(cf.isolated)

predictions <- predict(cf.isolated)

#calibration
#Ranking ITEs
tau.hat = predictions$predictions
rank.cf.isolated <- rep(NA, nrow(sample.cf))
table(quantile(tau.hat[folds == 1], probs = seq(0, 1, by=1/num.rankings)))
table(quantile(tau.hat[folds == 2], probs = seq(0, 1, by=1/num.rankings)))
table(quantile(tau.hat[folds == 3], probs = seq(0, 1, by=1/num.rankings)))
table(quantile(tau.hat[folds == 4], probs = seq(0, 1, by=1/num.rankings)))
table(quantile(tau.hat[folds == 5], probs = seq(0, 1, by=1/num.rankings)))
for (fold in seq(num.folds)) {
  tau.hat.quantiles <- quantile(tau.hat[folds == fold], probs = seq(0, 1, by=1/num.rankings))
  rank.cf.isolated[folds == fold] <- cut(tau.hat[folds == fold], tau.hat.quantiles, include.lowest=TRUE,labels=seq(num.rankings))
}
sample.cf$rank.cf.isolated = rank.cf.isolated

#CATE for each rank: OLS 
fit.isolated =
  glm(isolated ~ factor(rank.cf.isolated) + behavior.1:factor(rank.cf.isolated),
         data=sample.cf,
         family='gaussian')
summary(fit.isolated)
beta.ols = coef(fit.isolated)[6:10]
se.ols = coef(summary(fit.isolated))[,2][6:10]
ols.ate <- data.frame("OLS", paste0("Q", seq(num.rankings)), beta.ols, se.ols)
colnames(ols.ate) <- c("method", "ranking", "estimate", "std.err")
ols.ate

#CATE for each rank: AIPW
cate.cf.isolated.1 = average_treatment_effect(cf.isolated,
                                             subset=sample.cf$rank.cf.isolated==1)
cate.cf.isolated.2 = average_treatment_effect(cf.isolated, 
                                             subset=sample.cf$rank.cf.isolated==2)
cate.cf.isolated.3 = average_treatment_effect(cf.isolated,
                                             subset=sample.cf$rank.cf.isolated==3)
cate.cf.isolated.4 = average_treatment_effect(cf.isolated, 
                                             subset=sample.cf$rank.cf.isolated==4)
cate.cf.isolated.5 = average_treatment_effect(cf.isolated, 
                                             subset=sample.cf$rank.cf.isolated==5)

plot.aipw = rbind(cate.cf.isolated.1,cate.cf.isolated.2,cate.cf.isolated.3,cate.cf.isolated.4,cate.cf.isolated.5)
aipw.ate <- data.frame("CF", paste0("Q", seq(num.rankings)), plot.aipw[,1:2])
colnames(aipw.ate) <- c("method", "ranking", "estimate", "std.err")
aipw.ate

res <- rbind(aipw.ate, ols.ate)

#plot
f.res.isolated = ggplot(data = res) +
  aes(x = ranking, y = estimate*100, group = method, color = method) + 
  geom_point(position=position_dodge(0.2)) +
  geom_errorbar(aes(ymin=estimate*100-2*std.err*100, ymax=estimate*100+2*std.err*100), width=0, position=position_dodge(0.2)) + # add error bars (do so before geom_point so the points are on top of the error bars)
  geom_hline(yintercept=0, linetype="dotted", color='darkslategrey') +
  scale_y_continuous("Conditional average treatment effect on isolation \nwithin each rank (percentage points)") + 
  theme(axis.text.x = element_text(angle = 0), panel.grid = element_blank()) +
  theme(text=element_text(family="Helvetica", face="bold",  size=10, color="black" ))+
  xlab("Rank") +
  #ggtitle("Positive depression screening result") +
  theme(legend.position="bottom", legend.title = element_blank(), plot.title = element_text(hjust = 0.5))
print(f.res.isolated)

```

#CLAN
```{r}
sample.clan = sample.cf
sample.clan$high.ate = factor(ifelse(predictions$predictions>median(predictions$predictions),"More likely to be isolated with initial defection","Less likely to be isolated with initial defection"))

table(sample.clan$high.ate)

aggregate(sample.clan$degree.0, by=list(sample.clan$high.ate), FUN=mean)
t.test(sample.clan$degree.0, by=sample.clan$high.ate)

aggregate(sample.clan$coefLocal.0, by=list(sample.clan$high.ate), FUN=mean)
t.test(sample.clan$coefLocal.0, by=sample.clan$high.ate)

aggregate(sample.clan$coefGlobal.0, by=list(sample.clan$high.ate), FUN=mean)
t.test(sample.clan$coefGlobal.0, by=sample.clan$high.ate)

aggregate(sample.clan$alterPrevDegree.1, by=list(sample.clan$high.ate), FUN=mean)
t.test(sample.clan$alterPrevDegree.1, by=sample.clan$high.ate)

table(sample.clan$visibleWealth, by=sample.clan$high.ate)
chisq.test(sample.clan$visibleWealth, sample.clan$high.ate)

table(sample.clan$wealth, by=sample.clan$high.ate)
chisq.test(sample.clan$wealth, sample.clan$high.ate)

table(sample.clan$inequality, by=sample.clan$high.ate)
chisq.test(sample.clan$inequality, sample.clan$high.ate)

```

#conditional average treatment effects by wealth visibility and inequality
```{r regression_by_groups, echo=FALSE}
#low inequlaity, visible wealth
reg.everIsolated.low.visible = miceadds::glm.cluster(isolated ~ behavior.1, 
      data = sample.reg[sample.reg$inequality=="low" & sample.reg$visibleWealth==1,], 
      cluster = "gameID",
      family = binomial(link = "logit"))
alpha <- 0.05
x.everIsolated.low.visible <- summary(reg.everIsolated.low.visible)
y.everIsolated.low.visible <- confint(reg.everIsolated.low.visible, level=1-alpha)
coef.everIsolated.low.visible <- x.everIsolated.low.visible[,1]
LowerCL.everIsolated.low.visible <- y.everIsolated.low.visible[,1]
UpperCL.everIsolated.low.visible <- y.everIsolated.low.visible[,2]
p.everIsolated.low.visible <-x.everIsolated.low.visible[,4]
#odds raio
z.everIsolated.low.visible <- cbind(exp(coef.everIsolated.low.visible["behavior.1D"]), exp(LowerCL.everIsolated.low.visible["behavior.1D"]), exp(UpperCL.everIsolated.low.visible["behavior.1D"]), p.everIsolated.low.visible["behavior.1D"])
z.everIsolated.low.visible = data.frame(z.everIsolated.low.visible)
names(z.everIsolated.low.visible) = c("OR", "Lower CL", "Upper CL", "P-value")


#high inequality, visible wealth
reg.everIsolated.high.visible = miceadds::glm.cluster(isolated ~ behavior.1, 
      data = sample.reg[sample.reg$inequality=="high" & sample.reg$visibleWealth==1,], 
      cluster = "gameID",
      family = binomial(link = "logit"))
alpha <- 0.05
x.everIsolated.high.visible <- summary(reg.everIsolated.high.visible)
y.everIsolated.high.visible <- confint(reg.everIsolated.high.visible, level=1-alpha)
coef.everIsolated.high.visible <- x.everIsolated.high.visible[,1]
LowerCL.everIsolated.high.visible <- y.everIsolated.high.visible[,1]
UpperCL.everIsolated.high.visible <- y.everIsolated.high.visible[,2]
p.everIsolated.high.visible <-x.everIsolated.high.visible[,4]
#odds raio
z.everIsolated.high.visible <- cbind(exp(coef.everIsolated.high.visible["behavior.1D"]), exp(LowerCL.everIsolated.high.visible["behavior.1D"]), exp(UpperCL.everIsolated.high.visible["behavior.1D"]), p.everIsolated.high.visible["behavior.1D"])
z.everIsolated.high.visible = data.frame(z.everIsolated.high.visible)
names(z.everIsolated.high.visible) = c("OR", "Lower CL", "Upper CL", "P-value")


#low inequality, invisible wealth
reg.everIsolated.low.invisible = miceadds::glm.cluster(isolated ~ behavior.1, 
      data = sample.reg[sample.reg$inequality=="low" & sample.reg$visibleWealth==0,], 
      cluster = "gameID",
      family = binomial(link = "logit"))
alpha <- 0.05
x.everIsolated.low.invisible <- summary(reg.everIsolated.low.invisible)
y.everIsolated.low.invisible <- confint(reg.everIsolated.low.invisible, level=1-alpha)
coef.everIsolated.low.invisible <- x.everIsolated.low.invisible[,1]
LowerCL.everIsolated.low.invisible <- y.everIsolated.low.invisible[,1]
UpperCL.everIsolated.low.invisible <- y.everIsolated.low.invisible[,2]
p.everIsolated.low.invisible <-x.everIsolated.low.invisible[,4]
#odds raio
z.everIsolated.low.invisible <- cbind(exp(coef.everIsolated.low.invisible["behavior.1D"]), exp(LowerCL.everIsolated.low.invisible["behavior.1D"]), exp(UpperCL.everIsolated.low.invisible["behavior.1D"]), p.everIsolated.low.invisible["behavior.1D"])
z.everIsolated.low.invisible = data.frame(z.everIsolated.low.invisible)
names(z.everIsolated.low.invisible) = c("OR", "Lower CL", "Upper CL", "P-value")


#high inequality, invisible wealth
reg.everIsolated.high.invisible = miceadds::glm.cluster(isolated ~ behavior.1, 
      data = sample.reg[sample.reg$inequality=="high" & sample.reg$visibleWealth==0,], 
      cluster = "gameID",
      family = binomial(link = "logit"))
alpha <- 0.05
x.everIsolated.high.invisible <- summary(reg.everIsolated.high.invisible)
y.everIsolated.high.invisible <- confint(reg.everIsolated.high.invisible, level=1-alpha)
coef.everIsolated.high.invisible <- x.everIsolated.high.invisible[,1]
LowerCL.everIsolated.high.invisible <- y.everIsolated.high.invisible[,1]
UpperCL.everIsolated.high.invisible <- y.everIsolated.high.invisible[,2]
p.everIsolated.high.invisible <-x.everIsolated.high.invisible[,4]
#odds raio
z.everIsolated.high.invisible <- cbind(exp(coef.everIsolated.high.invisible["behavior.1D"]), exp(LowerCL.everIsolated.high.invisible["behavior.1D"]), exp(UpperCL.everIsolated.high.invisible["behavior.1D"]), p.everIsolated.high.invisible["behavior.1D"])
z.everIsolated.high.invisible = data.frame(z.everIsolated.high.invisible)
names(z.everIsolated.high.invisible) = c("OR", "Lower CL", "Upper CL", "P-value")



```

```{r}
#Low inequality, visible wealth
kable(z.everIsolated.low.visible)
#High inequality, visible wealth
kable(z.everIsolated.high.visible)
#Low inequality, invisible wealth
kable(z.everIsolated.low.invisible)
#High inequality, invisible wealth
kable(z.everIsolated.high.invisible)
```

